---
- name: Configure Nginx Web Server
  hosts: all
  become: true
  tasks:

    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Enable and start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Customize index.html
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <html>
          <body>
          <h1>Hello from Ansible — Web Server is Ready!</h1>
          <p>Deployed automatically by Mazen’s playbook.</p>
          </body>
          </html>
        owner: root
        group: root
        mode: '0644'

